#+latex_class: article
#+latex_class_options:
#+latex_header: \usepackage{algorithm}
#+latex_header: \usepackage{algorithmic}
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:
#+latex_compiler: pdflatex
#+date: \today


* アルゴリズム
次のテーブルを用いて値の計算を行い、Interporated KN model を用いて bigram, trigram の計算を行った。
** テーブル
#+CAPTION: 3-gram テーブルを作る
#+begin_example
<1 2 3 4 5 6> -> {<1 2 3> <2 3 4> <3 4 5> <4 5 6> <5 6 -1> <6 -1 -1> }
#+end_example

これを用いて次のようなテーブルを作成する

|-----+-----+-----|
| 1st | 2nd | 3rd |
|-----+-----+-----|
|   1 |   2 |   3 |
|   2 |   3 |   4 |
|   3 |   4 |   5 |
|   4 |   5 |   6 |
|   5 |   6 |  -1 |
|   6 |  -1 |  -1 |
|-----+-----+-----|


$C(w1, w2, w3)$ を検索するときは、[1st $$==$$ w1], [2nd $$==$$ w2], [3rd $==$ w3] と検索した結果の数を集計する。
$C(w1, w2)$ を検索するときは、 [1st $==$ w1] , [2nd $==$ w2] [3rd $!=$-1]と検索した結果の数を集計する。
$K(w2, w3)$ を検索するときは　[2nd $==$ w2] ,[3rd $==$ w3] と検索した結果の数から 1st の種類数を集計する。
$K(w2)$ を検索するときは、[2nd $==$ w2] と検索した結果の中から 1st の種類数を集計する。
$C(w1)$ を集計するときは、[1st $==$ w1] [2nd $!=$ -1]  と検索した結果を集計する。
TODO: FIX N = |u: c'(hu) > 0|
$N_{1+}^{'}(w1, w2 \cdot)$ を検索するときは、[1st $==$ w1], [2nd$==$w2] [3rd $!=$ -1] と検索した結果の種類数を集計する。
$N_{1+}^{'}(w1, \cdot)$ を検索するときは、[1st $==$ w1] [2rd $!=$ -1] と検索した結果の種類数を集計する。
$n_1$  を検索するときはこのテーブルの行数を集計する。
$n_2$ を検索するときはこのテーブルの [3rd $!=$ -1] な行数を集計する。
$n_3$ を検索するときはこのテーブルの [2nd $!=$ -1], [3rd $!=$ -1] な行数を集計する。
$\Sigma_w K(w2)$ を検索するときは、[2nd $==$ w2],[3rd $!=$ -1] を検索した結果から、1st, 3rd の組み合わせの数を集計する。
$\Sigma_w K()$ を検索するときは、[2nd $!=$ -1] を検索した結果から 1st, 2nd の組み合わせの数を集計する。

具体的な例を示すと、次のようになる。

** Interporated KN Model
   Interporated KN Model の bigram の式、trigram の式を次に示す。
   

